//! Build-time `DEPLOYER` override.
//!
//! Reads the `SPLITTER_DEPLOYER` env var (base58 Solana pubkey). When set,
//! the generated `DEPLOYER` const uses those bytes; otherwise it falls back
//! to the placeholder bytes in `src/constants.rs` (local tests only).
//!
//! No third-party deps: minimal base58 decode with std only so the
//! script stays usable under `cargo build-sbf` and locked CI builds.

use std::env;
use std::fs;
use std::path::Path;

const BASE58_ALPHABET: &[u8] = b"123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

/// Decode a base58 string into raw bytes. Returns `Err(msg)` on bad input.
fn base58_decode(input: &str) -> Result<Vec<u8>, String> {
    let input = input.trim();
    if input.is_empty() {
        return Err("empty string".to_string());
    }
    // Count leading '1's -> leading zero bytes.
    let leading_zeros = input.bytes().take_while(|&b| b == b'1').count();
    // Base-convert: result is big-endian base256.
    let mut num: Vec<u8> = vec![0];
    for c in input.bytes() {
        let digit = BASE58_ALPHABET
            .iter()
            .position(|&a| a == c)
            .ok_or_else(|| format!("invalid base58 character: '{}'", c as char))?;
        let mut carry = digit as u32;
        for b in num.iter_mut().rev() {
            let cur = (*b as u32) * 58 + carry;
            *b = (cur & 0xFF) as u8;
            carry = cur >> 8;
        }
        while carry > 0 {
            num.insert(0, (carry & 0xFF) as u8);
            carry >>= 8;
        }
    }
    // Strip leading zero byte added by the conversion loop, then prepend
    // the real leading zeros.
    let first_nonzero = num.iter().position(|&b| b != 0);
    let mut out = vec![0u8; leading_zeros];
    match first_nonzero {
        Some(i) => out.extend_from_slice(&num[i..]),
        None => {
            // Input was all '1's: `num` is a single zero; leading_zeros
            // already covers it.
            if out.is_empty() {
                out.push(0);
            }
        }
    }
    Ok(out)
}

fn main() {
    println!("cargo:rerun-if-env-changed=SPLITTER_DEPLOYER");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set by cargo");
    let dest = Path::new(&out_dir).join("splitter_deployer.rs");

    let override_addr = env::var("SPLITTER_DEPLOYER")
        .ok()
        .filter(|s| !s.trim().is_empty());

    let bytes: [u8; 32] = match override_addr {
        Some(addr) => {
            let raw =
                base58_decode(&addr).unwrap_or_else(|e| panic!("SPLITTER_DEPLOYER invalid: {e}"));
            if raw.len() != 32 {
                panic!(
                    "SPLITTER_DEPLOYER invalid: decoded to {} bytes, expected 32 (addr: {addr})",
                    raw.len()
                );
            }
            let mut arr = [0u8; 32];
            arr.copy_from_slice(&raw);
            if arr == [0u8; 32] {
                panic!("SPLITTER_DEPLOYER must not be the default (all-zero) pubkey");
            }
            println!("cargo:warning=SPLITTER_DEPLOYER override baked in: {addr}");
            arr
        }
        None => {
            // Placeholder fallback (local tests only). MUST match the
            // PLACEHOLDER_DEPLOYER_BYTES in src/constants.rs.
            [
                0xDE, 0xA0, 0xD0, 0xBE, 0x57, 0x14, 0x59, 0xCC, 0x1D, 0xDE, 0xE5, 0x53, 0xA1, 0x57,
                0x29, 0x6B, 0x17, 0xD0, 0x8F, 0x8F, 0x6B, 0x42, 0xC2, 0x6B, 0x35, 0x70, 0x2F, 0xC4,
                0xB4, 0x00, 0x00, 0x01,
            ]
        }
    };

    // Pretty-wrap at 16 bytes per line for readability.
    let hex: Vec<String> = bytes.iter().map(|b| format!("0x{b:02X}")).collect();
    let pretty = format!(
        "/// Generated by build.rs — do not edit.\n/// Source: $SPLITTER_DEPLOYER env var, or the placeholder fallback.\n\
         pub const DEPLOYER: Pubkey = Pubkey::new_from_array([\n    {},\n    {},\n]);\n",
        hex[..16].join(", "),
        hex[16..].join(", ")
    );
    fs::write(&dest, pretty).expect("failed to write splitter_deployer.rs");
}
