skip_local_validator = true

[toolchain]
solana_version = "4.1.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
splitter = "DPFAmcgGe7ZaLCRQAZ24Z9SJ8s5gaBWHHbKjLNWsWWBS"

[programs.devnet]
splitter = "DPFAmcgGe7ZaLCRQAZ24Z9SJ8s5gaBWHHbKjLNWsWWBS"


[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
test_ts = "pnpm exec ts-mocha -p tsconfig.json tests/**/*.test.ts"

[hooks]
